#ifndef POKEMONMODULE_GLOBAL_H
#define POKEMONMODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POKEMONMODULE_LIBRARY)
#  define POKEMONMODULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define POKEMONMODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // POKEMONMODULE_GLOBAL_H
